name: foodly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  
  flutter:
    sdk: flutter

  saudi_riyal_symbol: ^0.0.7
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  country_picker: ^2.0.23
  video_player: ^2.8.3
  rename: ^3.1.0
  audioplayers: ^6.1.0
  phone_otp_verification: 1.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  flutter_intl_phone_field: ^0.0.7
  cloud_firestore: ^5.2.0
  widget_to_marker: ^1.0.6
  change_app_package_name: ^1.1.0
  file_picker: ^8.0.3
  intl: ^0.20.2
  country_code_picker: ^3.0.0

 
 
 




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/Cairo-Bold.ttf
